name: InfluxDB3
version: 43a7875
slug: influxdb3
description: Scalable datastore for metrics, events, and real-time analytics
url: https://github.com/erik73/hassio-addons
panel_icon: mdi:chart-areaspline
startup: services
homeassistant: 0.92.0b2
hassio_api: true
arch:
- aarch64
- amd64
init: false
map:
- share:rw
- ssl
ports:
  8181/tcp: 8181
ports_description:
  8181/tcp: InfluxDB server
options:
  log_level: info
  influxd_log_level: warn
  reporting: true
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  envvars: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  influxd_log_level: list(debug|info|warn|error)?
  license_email: match(^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$)
  reporting: bool
  ssl: bool
  certfile: str
  keyfile: str
  envvars:
  - name: match(^INFLUXD_([A-Z0-9_])+$)
    value: str
image: ghcr.io/erik73/influxdb3/{arch}
